---
- include_tasks:        '../tasks/dependencies.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/shell_commands.yml'
- include_tasks:        '../tasks/apt_update.yml'
  when:                 install_files_result.changed 
                        or shell_commands_result.changed
- include_tasks:        '../tasks/apt_upgrade.yml'
  when:                 install_files_result.changed 
                        or shell_commands_result.changed
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/enable_services.yml'
- include_tasks:        '../tasks/start_services.yml'
